language: ruby
script: "rake"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx
services:
  - mongodb
